# -*- coding: utf-8 -*-
"""SVR_Samples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTmdOAwR4Gv1cV6qSQjg_Gd4WSTCUXzZ
"""

from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_regression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Veri oluştur
X, y = make_regression(n_samples=100, n_features=1, noise=0.1)

# Pipeline oluştur
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svr', SVR())
])

# Hiperparametre aralıklarını tanımla
param_grid = {
    'svr__C': [0.1, 1, 10],
    'svr__epsilon': [0.1, 0.2, 0.3],
    'svr__kernel': ['linear', 'rbf']
}

# Grid search ile en iyi parametreleri bul
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X, y)

# En iyi parametreleri ve skoru yazdır
print("En iyi parametreler:", grid_search.best_params_)
print("En iyi skor:", -grid_search.best_score_)

# En iyi modeli kullan
best_model = grid_search.best_estimator_